apiVersion: v1
kind: ConfigMap
metadata: 
 name: {{.Release.Name}}-config-map
 {{- template "p_ex_4.labels"}}
 namespace: default
data:
{{/* |- means that it will contain more than 1 value */}}
{{- with .Values.spanish_universities }}
 {{- range .}}
 spanish_universities: {{upper .}}
 {{- end }}
{{- end }}