apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
    type: db
    creationDate: {{.Values.data.creationDate}}
spec: 
 containers:
 {{- /* 
  This is a Helm comment
*/}}
 {{$version := "5.7"}}
  - image: mysql:{{$version}}
    name:  mysql